Migrate to Shapely 2.0+ (#22)
* Add instructions for testing

* Fix the check on shapely/GEOS

* WIP on base.py - compose instead of inheriting

* 12 tests of base and 4 of utils pass

* Whitespace

* Fix in plot

* 6 utils test pass, with 1 warning

* More adaptations -> 86 passed, 16 failed

* Implemen cache of _geometry for ShadeCollection and PVSegment

* Property coords and iterate over difference geometries 90 vs. 12

* Add method intersects to BaseSide

* Migrate PVRow

* Remove inheritance from GeometryCollection
* Add length property and intersects function

* Add centroid property to BaseSurface

* Fix plots

* All tests pass

* Update requirements

* Removed a line

* Bring README to relevance (links, etc.)

* Use dwithin rather than distance

The distance method would raise "RuntimeWarning: invalid value encountered in distance" when acting on a linestring which is a single point. The dwithin method does not.

* Fix all but 3 divide-by-zero RuntimeWarning

Where np.where was used, replaced by np.divide with a where argument

* Fix an error message and README

* Fix for failing Read the Docs build

We were getting the following error: "The sphinx.configuration key is missing. This key is now required, see our blog post for more information."

With the following blog post link:
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/

* Fix to fix?

* Restore missing path

* Remove ~=4.0 in sphinx requirement

* Fix sphinx exception

TypeError: not all arguments converted during string formatting

* Fix README.rst (solarfactors instead of openfactors)

Co-authored-by: Kevin Anderson <kevin.anderso@gmail.com>

* Fix README.rst (solarfactors instead of openfactors)

Co-authored-by: Kevin Anderson <kevin.anderso@gmail.com>

* Update README.rst

Co-authored-by: Kevin Anderson <kevin.anderso@gmail.com>

* Update README.rst

Co-authored-by: Kevin Anderson <kevin.anderso@gmail.com>

---------

Co-authored-by: Kevin Anderson <kevin.anderso@gmail.com>